[rtpengine]
# The internal IP for control and external IP for media
interface = eth0!$EXTERNAL_SIP_IP

# Control channel for Kamailio
listen-ng = 0.0.0.0:22222

# Port range for RTP media packets
port-min = 30000
port-max = 40000

# Logging level (7 is debug, 5 is standard info)
log-level = 5
log-stderr = true
